[package]
name = "b3_basic_wallet"
version = "0.0.0-alpha.17"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_wallet_lib = { path = "../lib/b3_wallet_lib" }
b3_utils = { path = "../lib/b3_utils" }
candid = { workspace = true }
ic-cdk = { workspace = true }