[package]
name = "b3_user"
version = "0.0.0-alpha.4"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_user_lib = { path = "../b3_user_lib" }
candid = "0.8.4"
ic-cdk = "0.7.4"
serde = { version = "1.0.162", features = ["derive"] }
