[package]
name = "b3_user"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_user_lib = { path = "../b3_user_lib" }
serde = "1.0"
candid = "0.8.4"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.10"