[package]
name = "b3_payment"
version = "0.0.10"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_helper_lib = { path = "../lib/b3_helper_lib" }
b3_permit_lib = { path = "../lib/b3_permit_lib" }
candid = { workspace = true }
ic-cdk = { workspace = true }