[package]
name = "b3_payment"
version = "0.0.10"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_utils = { path = "../lib/b3_utils" }
b3_operations = { path = "../lib/b3_operations" }
candid = { workspace = true }
ic-cdk = { workspace = true }