[workspace]
members = [
    "backend/b3_system",
    "backend/b3_wallet",
    "backend/b3_basic_wallet",
    "backend/lib/b3_utils",
    "backend/lib/b3_system_lib",
    "backend/lib/b3_wallet_lib",
    "backend/lib/b3_operations",
]

[workspace.dependencies]
candid = "0.9.1"
ic-cdk = "0.10.0"
serde = { version = "1", features = ["derive"] }
