[workspace]
members = [
    "backend/b3_system",
    "backend/b3_wallet",
    "backend/b3_simple_wallet",
    "backend/lib/b3_helper_lib",
    "backend/lib/b3_system_lib",
    "backend/lib/b3_wallet_lib",
    "backend/lib/b3_permit_lib",
]

[workspace.dependencies]
candid = "0.8.4"
ic-cdk = "0.8.0"