[package]
name = "b3_system"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_helper = { path = "../b3_helper" }
b3_system_lib = { path = "../b3_system_lib" }
candid = "0.8.4"
ic-cdk = "0.7.4"
