[package]
name = "b3_system"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_helper_lib = { path = "../../lib/b3_helper_lib" }
b3_system_lib = { path = "../../lib/b3_system_lib" }
candid = { workspace = true }
ic-cdk = { workspace = true }