[package]
name = "b3_signer"
version = "0.0.0-alpha.7"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3_signer_lib = { path = "../b3_signer_lib" }
b3_helper = { path = "../b3_helper" }
candid = "0.8.4"
ic-cdk = "0.7.4"
