[package]
name = "b3system"
version = "0.0.0-beta.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
b3system_lib = { path = "../lib/b3system_lib" }
b3_utils = { workspace = true }
candid = { workspace = true }
ic-cdk = { workspace = true }
